# [START add_project]
swagger: "2.0"
info:
  description: "A simple Google Cloud Endpoints API example."
  title: "Endpoints Example"
  version: "1.0.0"
host: "precisaser-1sti.appspot.com"
# [END add_project]
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "http"
paths:
  "/":
    get:
      description: "Returns a Hello World message."
      produces:
      - "application/json"
      operationId: "echo"
      responses:
        200:
          description: "Simple Hello World Message."
          schema:
            $ref: "#/definitions/echoMessage"
  "/name":
    get:
      description: "Returns greetings for the name given."
      produces:
      - "application/json"
      operationId: "greet"
      responses:
        200:
          description: "Returns Hello, + given name"
          schema:
            $ref: "#/definitions/echoMessage"
  echoMessage:
    properties:
      message:
        type: "string"
# This section requires all requests to any path to require an API key.
security:
- api_key: []
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  # This section configures authentication using Google API Service Accounts
  # to sign a json web token. This is mostly used for server-to-server
  # communication.
  google_jwt:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    # This must match the 'iss' field in the JWT.
    x-google-issuer: "jwt-client.endpoints.sample.google.com"
    # Update this with your service account's email address.
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/endpoints@precisaser-1sti.iam.gserviceaccount.com"
  # This section configures authentication using Google OAuth2 ID Tokens.
  # ID Tokens can be obtained using OAuth2 clients, and can be used to access
  # your API on behalf of a particular user.
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v1/certs"
